Remove `with` context on os.scandir
ki-tools/kitools-py pull request #11
Opened 2019-03-18 21:22 UTC by sergeyf

Makes it compatible with py3.5

2019-03-18 21:48 UTC, pcstout requested changes

2019-03-18 21:48 UTC, pcstout commented on src/kitools/data_adapters/synapse/synapse_adapter.py
> +        iter = os.scandir(local_path)
We should probably wrap this in a `try`/`finally`
```python
entries = os.scandir(local_path)
try:
    for entry in entries:
        if entry.is_dir(follow_symlinks=False):
            dirs.append(entry)
        else:
            files.append(entry)
finally:
    entries.close()
```

2019-03-18 21:56 UTC, sergeyf commented on src/kitools/data_adapters/synapse/synapse_adapter.py
> +        iter = os.scandir(local_path)
Gotcha.

2019-03-18 21:58 UTC, sergeyf commented
@pcstout done!

2019-03-19 00:44 UTC, hafen commented
That's great thanks @sergeyf

2019-03-19 00:44 UTC, hafen commented
I'll leave it up to @pcstout to merge

2019-03-19 00:52 UTC, pcstout approved these changes

2019-03-19 00:53 UTC, merged